### ISSUE TITLE
Key incorrect for fa variable

### ISSUE THREAD

**Issue by lwaldron** [elmoen/clustered_data_code#2]
The key given for the fa variable:
https://github.com/elmoen/clustered_data_code/blob/f887245b69f15f2e01a53ed1cc479a0feab8e664/Stata#L6

produces regression coefficients with opposite sign compared to what is reported in the publication. I think the correct key would be:

```
fattyacid = factor of 0, 1, or 2 indicating no treatment, vehicle control, or fatty acid treatment, respectively
```

Here is a reproducible example in R showing how I came to this conclusion. Note that I recoded fa as `"1" = "Vehicle Control", "0" = "No Treatment", "2" = "Fatty Acid Treatment"` in order to reproduce the coefficient of 3.15 reported on the first row of Table 3 (https://doi.org/10.1371/journal.pone.0146721.t003).

``` r
library(tidyverse)
library(readr)
Assignment4 <-
  read_csv(
    "https://raw.githubusercontent.com/elmoen/clustered_data_code/master/PtenAnalysisData.csv",
    col_types = cols(
      mouseid = col_factor(),
      fa = col_factor(),
      pten = col_factor(),
      somasize = col_double(),
      numctrl = col_double(),
      numpten = col_double(),
      prop = col_double(),
      meanss_pten = col_double(),
      meanss_all = col_double()
    )
  ) %>%
  mutate(fa = recode_factor(fa, "1" = "Vehicle Control", "0" = "No Treatment", "2" = "Fatty Acid Treatment"))
## https://github.com/elmoen/clustered_data_code/blob/f887245b69f15f2e01a53ed1cc479a0feab8e664/Stata#L6

rq1 <-
  filter(Assignment4, fa %in% c("Vehicle Control", "Fatty Acid Treatment")) %>%
  filter(pten == "0")

lm(somasize ~ fa, data = rq1)
#> 
#> Call:
#> lm(formula = somasize ~ fa, data = rq1)
#> 
#> Coefficients:
#>            (Intercept)  faFatty Acid Treatment  
#>                 96.862                   3.151
boxplot(somasize ~ fa, data = rq1)
```

![](https://i.imgur.com/oPB83TR.png)

<sup>Created on 2021-05-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by elmoen** [comment]
Thank you for bringing this to my attention! I will take a look later this week and resolve.

Best,
Erika

From: Levi Waldron ***@***.***>
Reply-To: elmoen/clustered_data_code ***@***.***>
Date: Sunday, May 16, 2021 at 12:21 PM
To: elmoen/clustered_data_code ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elmoen/clustered_data_code] Key incorrect for fa variable (#2)


The key given for the fa variable:
https://github.com/elmoen/clustered_data_code/blob/f887245b69f15f2e01a53ed1cc479a0feab8e664/Stata#L6<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felmoen%2Fclustered_data_code%2Fblob%2Ff887245b69f15f2e01a53ed1cc479a0feab8e664%2FStata%23L6&data=04%7C01%7CErika.L.Moen%40dartmouth.edu%7C4a7074dd8247493b7d3608d91886b06b%7C995b093648d640e5a31ebf689ec9446f%7C0%7C1%7C637567789039303618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=126ROLpNwMlK8U8PcSFbQmKV7zuNgioKAkO8Hl9%2B4VY%3D&reserved=0>

produces regression coefficients with opposite sign compared to what is reported in the publication. I think the correct key would be:

fattyacid = factor of 0, 1, or 2 indicating no treatment, vehicle control, or fatty acid treatment, respectively

Here is a reproducible example in R showing how I came to this conclusion. Note that I recoded fa as "1" = "Vehicle Control", "0" = "No Treatment", "2" = "Fatty Acid Treatment" in order to reproduce the coefficient of 3.15 reported on the first row of Table 3 (https://doi.org/10.1371/journal.pone.0146721.t003<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1371%2Fjournal.pone.0146721.t003&data=04%7C01%7CErika.L.Moen%40dartmouth.edu%7C4a7074dd8247493b7d3608d91886b06b%7C995b093648d640e5a31ebf689ec9446f%7C0%7C1%7C637567789039303618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w2YZ4PHEwHknAxYm1PPg86nBNExOfCjYm3jjMMqLG%2Bk%3D&reserved=0>).

library(tidyverse)

library(readr)

Assignment4 <-

  read_csv(

    "https://raw.githubusercontent.com/elmoen/clustered_data_code/master/PtenAnalysisData.csv",

    col_types = cols(

      mouseid = col_factor(),

      fa = col_factor(),

      pten = col_factor(),

      somasize = col_double(),

      numctrl = col_double(),

      numpten = col_double(),

      prop = col_double(),

      meanss_pten = col_double(),

      meanss_all = col_double()

    )

  ) %>%

  mutate(fa = recode_factor(fa, "1" = "Vehicle Control", "0" = "No Treatment", "2" = "Fatty Acid Treatment"))

## https://github.com/elmoen/clustered_data_code/blob/f887245b69f15f2e01a53ed1cc479a0feab8e664/Stata#L6



rq1 <-

  filter(Assignment4, fa %in% c("Vehicle Control", "Fatty Acid Treatment")) %>%

  filter(pten == "0")



lm(somasize ~ fa, data = rq1)

#>

#> Call:

#> lm(formula = somasize ~ fa, data = rq1)

#>

#> Coefficients:

#>            (Intercept)  faFatty Acid Treatment

#>                 96.862                   3.151

boxplot(somasize ~ fa, data = rq1)

[Image removed by sender.]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fbf4145bdbfc2662a86f6ddbea84b9893c121ea89e4cf9834278ea8c2a2c32489%2F68747470733a2f2f692e696d6775722e636f6d2f6f5042383354522e706e67&data=04%7C01%7CErika.L.Moen%40dartmouth.edu%7C4a7074dd8247493b7d3608d91886b06b%7C995b093648d640e5a31ebf689ec9446f%7C0%7C1%7C637567789039313613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8VHsmC96uDA8ttMIi245N7wvxZ4hbfUzVJGdusJeJCw%3D&reserved=0>

Created on 2021-05-16 by the reprex package<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Freprex.tidyverse.org%2F&data=04%7C01%7CErika.L.Moen%40dartmouth.edu%7C4a7074dd8247493b7d3608d91886b06b%7C995b093648d640e5a31ebf689ec9446f%7C0%7C1%7C637567789039313613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ul26TiNV9qqHPtyTFIwzMNVoeWOfvY6xO6SZAIPUFls%3D&reserved=0> (v1.0.0)

**Comment by elmoen** [comment]
After verification I did in fact change the key as you suggested. Thank you for catching that! I hope you find the dataset useful!

**Comment by lwaldron** [comment]
Yes, it's a great teaching resource and I am using it to teach a biostatistics course (https://bios2.waldronlab.io). Thank you!!
